'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(x,d=1)=>x==null?'Not reached':Number(x).toLocaleString(undefined,{maximumFractionDigits:d}),pct=x=>fmt(x*100)+'%';
const st={run:null,compare:null,cohort:'all',floor:1,metric:'population_median',focused:false,session:null,defaults:null};
async function api(path,body){const r=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw Error(d.error||r.statusText);return d;}
function fail(e){$('game-error').textContent=e.message||e;$('game-error').hidden=false;}
function metric(label,value,note=''){return `<div class="metric"><span>${esc(label)}</span><strong>${esc(value)}</strong><span>${esc(note)}</span></div>`;}
function members(run=st.run){return run.players.filter(p=>st.cohort==='all'||p.policy===st.cohort);}
function summary(run,f){const row=run.floors[f-1];return st.cohort==='all'?row:row?.policies[st.cohort];}
const dayMetrics={population_median:'Half the players',mean_days:'Average among players who reached it',population_p90:'90% of players'};
function fastestAt(run,f){return members(run).flatMap(p=>p.milestones.filter(m=>m.floor===f).map(m=>({day:m.day,player:p}))).sort((a,b)=>a.day-b.day||a.player.id-b.player.id)[0];}
function daysText(value){return value>0&&value<.01?'Less than 0.01 day':`${fmt(value,2)} ${value===1?'day':'days'}`;}
function dayExplanation(run,f,key){
 const r=summary(run,f),target=`defeat floor ${f} monsters`;
 if(!r)return `Floor ${f} was not tested in this simulation.`;
 if(!r.players)return 'No players using this strategy were included in this simulation.';
 const who=key==='population_p90'?'90% of the players':'at least half the players';
 if(r[key]==null)return key==='mean_days'?`No players became able to ${target} within ${run.config.days} days.`:`Not reached within ${run.config.days} days: ${who} had not become able to ${target}.`;
 if(key==='mean_days')return `${daysText(r[key])} on average from starting to become able to ${target}. Only the ${r.reached} players who reached this floor are included.`;
 return `${daysText(r[key])} from starting until ${who} could ${target}.`;
}
function chartExplanation(run,f,key,value){
 const r=summary(run,f);
 if(!r)return `Floor ${f} was not tested in this simulation.`;
 if(!r.players)return 'No players using this strategy were included in this simulation.';
 const reached=`${r.reached} of ${r.players} players became able to defeat floor ${f} monsters within ${run.config.days} days.`;
 if(key==='fastest'){const best=fastestAt(run,f);return best?`${daysText(best.day)} from starting for the fastest player to become able to defeat floor ${f} monsters.\nPlayer #${best.player.id} · ${run.policy_definitions[best.player.policy].name}.`:`No player became able to defeat floor ${f} monsters within ${run.config.days} days.`;}
 if(dayMetrics[key])return dayExplanation(run,f,key)+'\n'+reached;
 if(key==='reach_fraction')return `${fmt(value)}% — ${reached}`;
 if(key==='reached')return reached+'\nThe number needed to defeat the warden has not been measured.';
 return value==null?`No hunts were attempted on floor ${f}.`:`${fmt(value)}% of hunts on floor ${f} ended in victory for these players. Deaths and escapes count as unsuccessful hunts.`;
}
function settings(){const c={...st.defaults.config,workers:0},form=new FormData($('game-form'));for(const [k,v] of form)if(k!=='policies')c[k]=Number(v);c.policies=form.getAll('policies');if(!c.policies.length)throw Error('Choose at least one strategy');return c;}
async function history(id){const {runs,errors}=await api('/api/game/runs');if(errors.length)fail(errors.join('; '));const wanted=id||st.run?.run_id,oldCompare=st.compare?.run_id;
 const options=runs.map(r=>`<option value="${r.run_id}">${r.run_id} · engine ${esc(r.engine_source.version)} · ${r.config.players} players / ${r.config.days} days · seed ${r.config.seed}</option>`).join('');
 $('game-run-select').innerHTML=options||'<option value="">No actual-engine runs yet</option>';$('game-compare').innerHTML='<option value="">No comparison</option>'+options;
 if(runs.some(r=>r.run_id===wanted))$('game-run-select').value=wanted;if(oldCompare)$('game-compare').value=oldCompare;
 if($('game-run-select').value)await load($('game-run-select').value);
}
let sequence=0;
async function load(id){const serial=++sequence,run=await api('/api/game/runs/'+id);if(serial!==sequence)return;st.run=run;if(st.cohort!=='all'&&!run.config.policies.includes(st.cohort))st.cohort='all';st.floor=Math.min(st.floor,run.config.max_floor);$('game-results').hidden=false;$('game-download').hidden=false;$('game-download').href='/api/game/runs/'+id+'.json';$('game-download').download=id+'.json';render();}
function chart(id,key,title,max){const el=$(id),n=st.focused?Math.min(st.run.config.max_floor,Math.max(10,Math.ceil(Math.max(...members().map(p=>p.ready_floor))/10)*10)):st.run.config.max_floor;
 const vals=run=>Array.from({length:n},(_,i)=>{const r=summary(run,i+1);if(!r)return null;if(key==='hunt'){const a=members(run).map(p=>p.floors[i+1]||{});const attempts=a.reduce((x,p)=>x+(p.attempts||0),0);return attempts?a.reduce((x,p)=>x+(p.wins||0),0)/attempts*100:null;}return r[key]==null?null:r[key]*(key==='reach_fraction'?100:1);});
 const series=[{run:st.run,key,color:'#63d5c2',values:vals(st.run)}];
 if(dayMetrics[key])series.push({run:st.run,key:'fastest',color:'#c9a6ec',values:Array.from({length:n},(_,i)=>fastestAt(st.run,i+1)?.day??null)});
 if(st.compare)series.push({run:st.compare,key,color:'#e0c17a',comparison:true,values:vals(st.compare)});
 const w=Math.max(270,el.clientWidth),h=290,left=52,right=18,top=32,bottom=52,finite=series.flatMap(s=>s.values).filter(x=>x!=null),ceiling=max||Math.max(1,...finite)*1.1,X=f=>left+(f-1)/Math.max(1,n-1)*(w-left-right),Y=v=>h-bottom-v/ceiling*(h-top-bottom);
 let svg=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="${title}">`;
 svg+=`<text x="${left}" y="16">${dayMetrics[key]?'Days since starting':key==='reached'?'Number of players':'Percent of '+(key==='hunt'?'hunts won':'players')}</text><text x="${w/2}" y="${h-3}" text-anchor="middle">Monster floor</text>`;
 for(let i=0;i<=4;i++){const v=ceiling*i/4;svg+=`<line x1="${left}" x2="${w-right}" y1="${Y(v)}" y2="${Y(v)}" stroke="#34434b" stroke-dasharray="2 5"/><text x="${left-8}" y="${Y(v)+5}" text-anchor="end">${fmt(v,ceiling<5?1:0)}</text>`;}
 for(const f of [...new Set([1,...[.25,.5,.75,1].map(x=>Math.max(1,Math.round(x*n)))])])svg+=`<text x="${X(f)}" y="${h-28}" text-anchor="middle">${f}</text>`;
 for(const s of series){let d='',connected=false;for(let i=0;i<n;i++){const v=s.values[i];if(v==null){connected=false;continue;}d+=`${connected?'L':'M'}${X(i+1)},${Y(v)} `;connected=true;svg+=`<circle cx="${X(i+1)}" cy="${Y(v)}" r="2" fill="${s.color}"/>`;}svg+=`<path d="${d}" stroke="${s.color}" fill="none" stroke-width="2" ${s.key==='fastest'?'stroke-dasharray="2 3"':s.comparison?'stroke-dasharray="6 4"':''}/>`;}
 if(!finite.length)svg+=`<text x="${w/2}" y="130" text-anchor="middle">No result within ${st.run.config.days} days</text>`;
 el.innerHTML=svg+'</svg>';
 function point(e){const f=Math.max(1,Math.min(n,Math.round(1+(e.clientX-el.getBoundingClientRect().left-left)/(w-left-right)*(n-1)))),tip=$('tooltip');
  tip.textContent=`Floor ${f} monsters\n\n`+series.map(s=>(s.comparison?`Comparison · ${s.run.config.players} players · ${s.run.config.days} days · seed ${s.run.config.seed}\n`:'')+chartExplanation(s.run,f,s.key,s.values[f-1])).join('\n\n');
  tip.hidden=false;tip.style.left='8px';tip.style.top='8px';
  tip.style.left=Math.max(8,Math.min(e.clientX+12,innerWidth-tip.offsetWidth-8))+'px';tip.style.top=Math.max(8,Math.min(e.clientY+12,innerHeight-tip.offsetHeight-8))+'px';return f;
 }
 el.onpointermove=point;el.onclick=e=>{st.floor=point(e);floorDetail();};el.onpointerleave=()=>$('tooltip').hidden=true;
}
function charts(){if(!st.run)return;
 $('tooltip').hidden=true;
 const who=st.metric==='mean_days'?'The average includes only players who reached each floor.':st.metric==='population_p90'?'A point appears when 90% of players can defeat that floor’s monsters.':'A point appears when at least half the players can defeat that floor’s monsters.';
 $('game-days-note').textContent=`Total calendar days since starting. ${who} Gaps mean this was not reached within ${st.run.config.days} days. Becoming able means winning at least ${Math.ceil(st.run.config.readiness_trials*st.run.config.readiness_threshold)} of ${st.run.config.readiness_trials} test fights with owned gear and full health and energy.`;
 $('game-days-legend').innerHTML=`<span class="cyan">━ ${esc(dayMetrics[st.metric])}</span><span class="purple">┄ Fastest player observed</span>${st.compare?'<span class="gold">┄ Comparison: '+esc(dayMetrics[st.metric])+'</span>':''}`;
 for(const node of document.querySelectorAll('[data-chart-context]'))node.textContent=`${members().length} ${st.cohort==='all'?'players':st.run.policy_definitions[st.cohort].name+' players'} · ${st.run.config.days} simulated days${node.dataset.chartContext==='days'?' · '+dayMetrics[st.metric]:''}`;
 chart('game-days-chart',st.metric,'Days until players can defeat monsters on each floor');chart('game-reach-chart','reach_fraction','Percentage of players able to defeat each floor’s monsters',100);chart('game-wins-chart','hunt','Percentage of hunts won on each floor',100);chart('game-hunters-chart','reached','Players able to defeat each floor’s monsters');}
function render(){const r=st.run,ps=members(),sorted=ps.map(p=>p.ready_floor).sort((a,b)=>a-b),mid=(sorted[Math.floor((sorted.length-1)/2)]+sorted[Math.floor(sorted.length/2)])/2;
 $('game-meta').textContent=`Actual engine ${r.engine_source.version} · ${r.config.players} players · ${r.config.days} days · ${fmt(r.duration_seconds)}s · ${r.execution.workers} CPUs. ${r.boundaries.world_access}`;
 $('game-comparison').hidden=!st.compare;if(st.compare){const c=st.compare,diff=Object.keys(r.config).filter(k=>k!=='workers'&&JSON.stringify(r.config[k])!==JSON.stringify(c.config[k]));$('game-comparison').textContent=`Gold dashed line: ${c.run_id}. Changed settings: ${diff.join(', ')||'none'}. ${c.engine_source.sha256===r.engine_source.sha256?'Same engine source.':'Different game source; not an isolated settings comparison.'} ${c.runner_sha256===r.runner_sha256?'Same runner source.':'Different runner/policies; interpret with care.'}`;}
 $('game-metrics').innerHTML=metric('Median ready floor',fmt(mid),`${ps.length} experimental players`)+metric('Reached last floor',`${ps.filter(p=>p.ready_floor>=r.config.max_floor).length} / ${ps.length}`,'Other players remain censored')+metric('Mean active time',fmt(ps.reduce((a,p)=>a+p.active_minutes,0)/ps.length)+' minutes','Includes navigation and purchases')+metric('Engine actions',fmt(ps.reduce((a,p)=>a+p.counters.actions,0),0),'Actual core calls during play');
 $('game-cohorts').innerHTML=[['all','Whole swarm','#e3e4d5'],...r.config.policies.map(k=>[k,r.policy_definitions[k].name,r.policy_definitions[k].color])].map(([k,n,c])=>`<button data-cohort="${k}" aria-pressed="${st.cohort===k}" class="${st.cohort===k?'active':''}" style="color:${c}">${esc(n)}</button>`).join('');
 $('game-floor').max=$('game-floor-slider').max=r.config.max_floor;const selected=$('game-player').value;$('game-player').innerHTML=ps.map(p=>`<option value="${p.id}">#${p.id} · ${esc(r.policy_definitions[p.policy].name)} · floor ${p.ready_floor}</option>`).join('');if(ps.some(p=>String(p.id)===selected))$('game-player').value=selected;charts();floorDetail();playerDetail();}
function floorDetail(){if(!st.run)return;const f=st.floor,r=summary(st.run,f),w=st.run.floors[f-1].warden;$('game-floor').value=$('game-floor-slider').value=f;$('game-floor-detail').innerHTML=`<p class="floor-explanation">${esc(dayExplanation(st.run,f,st.metric))}</p><div class="metrics">${metric('Can defeat floor '+f+' monsters',`${r.reached} / ${r.players} players`,pct(r.reach_fraction))}${metric('Time until half the players can win',r.population_median==null?'Not reached':daysText(r.population_median),'Since starting')}${metric('Average time among those who reached it',r.mean_days==null?'Not reached':daysText(r.mean_days),'Since starting')}${metric('Players needed to defeat the warden','Not measured','Requires shared-world battles')}</div><p>${esc(w.name)} · actual library shared HP ${fmt(w.shared_hp,0)} · regeneration ${pct(w.regen_fraction_per_hour)} / hour. ${w.quorum==null?'This is not a milestone pledge floor.':`Current milestone pledge quorum: ${w.quorum}. Quorum alone is not proof of victory.`}</p><p class="chart-note">These are current engine parameters. The proposed simultaneous-healing warden rules have not been substituted.</p>`;}
function playerDetail(){const p=members().find(p=>p.id===Number($('game-player').value));if(!p)return;const d=p.final;$('game-replay').disabled=!p.trace;$('game-replay-status').textContent=p.trace?`${p.trace.length} recorded reads, actions and world inputs. Engine RNG counter ${d.rng_counter}.`:'Full trace not stored for this player; choose a traced player or increase Complete player traces.';
 $('game-player-detail').innerHTML=`<div class="metrics">${metric('Character level',d.level)}${metric('Gold / bank',`${fmt(d.gold)} / ${fmt(d.bank)}`)}${metric('Weapon slots',d.slots,'Actual engine state')}${metric('Next floor probe',p.last_probe?pct(p.last_probe.win_rate):'No probe')}</div><p>Held: ${d.held.map(esc).join(', ')}. Training: ${esc(JSON.stringify(d.training))}.</p><div class="bars">${Object.entries(p.gold_ledger).map(([k,v])=>`<div class="bar-label"><span>${esc(k)}</span><span>${fmt(v)}</span></div>`).join('')}</div><p class="chart-note">Signed gold ledger from the game; deposits and withdrawals are transfers. No simulated price formula is used.</p><details open><summary>Decision blocks & latest hunt probes</summary><pre>${esc(JSON.stringify({blocks:p.bottlenecks,nextFloorProbe:p.last_probe},null,2))}</pre></details><details><summary>Recent actual game actions</summary><pre>${esc(JSON.stringify(p.recent_actions,null,2))}</pre></details><details><summary>Weekly progress / final document</summary><pre>${esc(JSON.stringify({timeline:p.timeline.filter((x,i)=>i%7===0||i===p.timeline.length-1),state_sha256:p.state_sha256,final:d},null,2))}</pre></details>`;}
async function inspect(body){$('inspect-start').disabled=true;try{const d=await api('/api/game/inspect',body);st.session=d.session;const s=d.scene,m=s.meters;$('inspect-state').innerHTML=`<p class="eyebrow">${esc(s.eyebrow)}</p><h3>${esc(s.headline)}</h3>${m?`<div class="metrics">${metric('HP',`${m.hp} / ${m.hp_max}`)}${metric('Energy',`${m.energy} / ${m.energy_max}`)}${metric('Gold / XP',`${m.gold} / ${m.xp}`)}${metric('Virtual elapsed time',fmt(d.seconds/3600)+' hours')}</div>`:'<p class="muted">Story transition · the engine does not emit meters on this scene.</p>'}${s.enemy?enemyCard(s.enemy,s.banner):''}<p>${esc(d.receipt.headline)}</p>${d.receipt.body_lines.map(x=>`<p>${esc(x)}</p>`).join('')}<p class="chart-note">${esc(d.receipt.refusal||d.receipt.shard_note)}</p><div class="inspect-actions">${s.options.map(o=>`<button data-game-action="${esc(o.id)}" ${o.locked?'disabled':''}>${esc(o.label)}${o.hint?`<span>${esc(o.hint)}</span>`:''}</button>`).join('')}</div><div class="run-actions"><button data-game-wait="2700">Wait 45 minutes</button><button data-game-wait="86400">Wait one day</button></div><p class="chart-note">Engine RNG ${d.rng_counter} · ${d.trace_length} recorded inputs · ${esc(d.state_sha256.slice(0,16))}</p><details><summary>Exact engine state</summary><pre>${esc(JSON.stringify(d.player,null,2))}</pre></details>`;}catch(e){fail(e);}finally{$('inspect-start').disabled=false;}}
let jobSeen=null;
async function poll(){try{const j=await api('/api/status');$('game-run').disabled=j.status==='running';$('game-progress').hidden=j.status!=='running';$('game-progress').value=j.fraction||0;$('game-status').textContent=j.status==='running'?`${j.stage} · ${j.completed||0}/${j.total||'…'} · ${j.workers} CPUs`:j.status==='complete'?`Saved in ${fmt(j.seconds)}s`:j.status==='error'?'Run failed':'Ready';if(j.status==='error')fail(j.error);if(j.status==='complete'&&j.backend==='actual-game-engine'&&j.run_id!==jobSeen){jobSeen=j.run_id;await history(j.run_id);}}catch(e){fail(e);}setTimeout(poll,1500);}
$('game-form').onsubmit=async e=>{e.preventDefault();$('game-error').hidden=true;try{$('game-run').disabled=true;$('game-status').textContent='Starting actual-engine run…';$('game-progress').hidden=false;$('game-progress').value=0;await api('/api/game/runs',settings());}catch(e){fail(e);$('game-run').disabled=false;}};
$('game-run-select').onchange=e=>load(e.target.value).catch(fail);$('game-compare').onchange=async e=>{try{st.compare=e.target.value?await api('/api/game/runs/'+e.target.value):null;render();}catch(e){fail(e);}};
$('game-copy').onclick=()=>{if(!st.run)return;for(const el of $('game-form').elements){if(el.name==='policies')el.checked=st.run.config.policies.includes(el.value);else if(el.name in st.run.config)el.value=st.run.config[el.name];}st.defaults.config={...st.defaults.config,...st.run.config};$('game-form').scrollIntoView({behavior:'smooth'});};
$('game-cohorts').onclick=e=>{const b=e.target.closest('[data-cohort]');if(b){st.cohort=b.dataset.cohort;render();}};$('game-quantiles').onclick=e=>{const b=e.target.closest('[data-metric]');if(b){st.metric=b.dataset.metric;for(const el of $('game-quantiles').querySelectorAll('[data-metric]'))el.classList.toggle('active',el===b);charts();floorDetail();}};
$('game-focus').onclick=()=>{st.focused=!st.focused;$('game-focus').textContent=st.focused?'Show all floors':'Zoom to reached floors';charts();};
for(const id of ['game-floor','game-floor-slider'])$(id).oninput=e=>{st.floor=Math.max(1,Math.min(st.run.config.max_floor,Number(e.target.value)||1));floorDetail();};
$('game-player').onchange=playerDetail;$('game-replay').onclick=async()=>{try{$('game-replay').disabled=true;$('game-replay-status').textContent='Replaying recorded actions through the actual engine…';const r=await api('/api/game/replay',{run_id:st.run.run_id,player:Number($('game-player').value)});$('game-replay-status').textContent=r.match?`MATCH: complete document, scene and RNG · ${r.actions} inputs · ${r.state_sha256}`:'MISMATCH: current engine does not reproduce this player';}catch(e){$('game-replay-status').textContent=e.message;}finally{$('game-replay').disabled=false;}};
$('inspect-start').onclick=()=>inspect({seed:Number($('game-form').elements.seed.value)});$('inspect-state').onclick=e=>{const b=e.target.closest('button');if(b&&st.session){for(const el of $('inspect-state').querySelectorAll('button'))el.disabled=true;inspect({session:st.session,...(b.dataset.gameWait?{wait_seconds:Number(b.dataset.gameWait)}:{action:b.dataset.gameAction})});}};
let resize;addEventListener('resize',()=>{clearTimeout(resize);resize=setTimeout(charts,100);});
(async()=>{try{st.defaults=await api('/api/game/defaults');$('engine-version').textContent=`Imported game ${st.defaults.source.version}`;$('source-summary').textContent='Calls '+st.defaults.source.engine+' — the same entry point used by worldd.';$('source-code').textContent=JSON.stringify(st.defaults.source,null,2);const d=await api('/api/defaults');$('cpu-label').textContent=d.cpus+' CPUs available';$('game-policies').innerHTML=Object.entries(st.defaults.policies).map(([k,p])=>`<label class="policy-option" style="--policy:${p.color}" title="${esc(p.description)}"><input type="checkbox" name="policies" value="${k}" checked>${esc(p.name)}</label>`).join('');await history();poll();}catch(e){fail(e);}})();

function enemyCard(e,banner){return `<div class="engine-enemy">${banner?`<img src="/game-art/${encodeURIComponent(banner)}.png" alt="${esc(e.name)}">`:''}<div><h3>${esc(e.name)} · ${esc(e.specimen)} · ${esc(e.profile?.type||'plain')}</h3><p>HP ${fmt(e.hp,0)} / ${fmt(e.hp_max,0)} · ATK ${fmt(e.atk,0)} · DEF ${fmt(e.def,0)} · SPEED ${fmt(e.mspd,0)}</p><p>Gap ${e.gap} · ${esc(e.range)} · ${esc(e.dtype)} in your hand</p><p class="muted">${esc(e.story||e.lore)}</p><details><summary>Actual monster profile & drops</summary><pre>${esc(JSON.stringify({profile:e.profile,drops:e.drops},null,2))}</pre></details></div></div>`;}
