// Development browser evidence only. The simulator itself has no browser dependency.
// PLAYWRIGHT_PATH=/absolute/path/to/playwright/index.mjs node simulation/verification/walkthrough.mjs
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath, pathToFileURL} from 'node:url';
const modulePath=process.env.PLAYWRIGHT_PATH;
const {chromium}=await import(modulePath?pathToFileURL(modulePath).href:'playwright');
const out=path.join(path.dirname(fileURLToPath(import.meta.url)),'001');
await fs.mkdir(out,{recursive:true});
const base=process.env.SIMULATION_URL||'http://127.0.0.1:8766';
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1080},deviceScaleFactor:1});
const issues=[];page.on('pageerror',e=>issues.push(e.message));
const observations={date:new Date().toISOString(),checks:[],screenshots:[]};
const record=(name,details)=>observations.checks.push({name,details});
const shot=async(name,locator)=>{await (locator||page).screenshot({path:path.join(out,name+'.png')});observations.screenshots.push(name+'.png');};
try {
 await page.goto(base);await page.locator('#results').waitFor({state:'visible'});
 await page.evaluate(()=>document.fonts.ready);
 const manifest=await (await page.request.get(base+'/api/runs')).json();
 const baseline=manifest.runs.find(r=>r.config.group_hp_scale===1&&r.config.players===24&&r.config.days===120);
 const comparison=manifest.runs.find(r=>r.config.group_hp_scale===.5&&r.config.players===24&&r.config.days===120);
 if(!baseline||!comparison)throw Error('Expected baseline and one-factor comparison created through the UI');
 const original=await (await page.request.get(`${base}/api/runs/${baseline.run_id}`)).json();
 await page.locator('#run-select').selectOption(baseline.run_id);
 await page.waitForFunction(id=>document.querySelector('#download').href.includes(id),baseline.run_id);
 await page.locator('#cohort-filters [data-policy="tactician"]').click();
 await page.locator('#floor-number').fill('6');
 const detail=await page.locator('#floor-detail').innerText();
 const expected=original.floors[5].policies.tactician;
 record('Floor 6 / tactician', {visible:detail,expected});
 if(!detail.includes(`Reached: ${expected.reached} / ${expected.players}`))throw Error('Floor/cohort reach count does not match JSON');
 await page.locator('#days-chart').scrollIntoViewIfNeeded();
 const box=await page.locator('#days-chart').boundingBox();
 await page.mouse.move(box.x+52+5/99*(box.width-70),box.y+120);
 await page.locator('#tooltip').waitFor({state:'visible'});
 const tip=await page.locator('#tooltip').innerText();
 record('Graph hover', {visible:tip,expectedMean:expected.mean_days});
 if(!tip.includes('Floor 6'))throw Error('Tooltip chose the wrong floor');
 const formatted=expected.mean_days.toLocaleString('en-US',{maximumFractionDigits:1});
 if(!tip.includes(formatted))throw Error('Tooltip mean does not match JSON');
 await shot('02-tooltip');
 await page.mouse.move(0,0);
 await page.locator('#cohort-filters [data-policy="all"]').click();
 await page.locator('#compare-select').selectOption(comparison.run_id);
 await page.locator('#compare-meta').waitFor({state:'visible'});
 record('Run comparison',await page.locator('#compare-meta').innerText());
 await shot('03-charts',page.locator('.chart-grid'));
 await page.locator('[data-range="reached"]').click();
 record('Focus reached floors',await page.locator('#graph-range-label').innerText());
 await shot('07-focused-charts',page.locator('.chart-grid'));
 await page.locator('[data-range="full"]').click();
 await page.locator('#floor-number').fill('100');
 const late=await page.locator('#floor-detail').innerText();
 record('Unreached floor 100',late);
 if(!late.includes('Mean among reached: Not reached')||!late.includes('0 qualified hunters')||!late.includes('Reference FAILS'))throw Error('Late-floor censoring or reference qualification is misleading');
 await shot('04-unreached-floor',page.locator('.floor-panel'));
 await page.locator('#run-select').selectOption(comparison.run_id);
 await page.waitForFunction(id=>document.querySelector('#download').href.includes(id),comparison.run_id);
 await page.locator('#run-select').selectOption(baseline.run_id);
 await page.waitForFunction(id=>document.querySelector('#download').href.includes(id),baseline.run_id);
 const [download]=await Promise.all([page.waitForEvent('download'),page.locator('#download').click()]);
 const downloaded=JSON.parse(await fs.readFile(await download.path(),'utf8'));
 if(downloaded.deterministic_sha256!==original.deterministic_sha256)throw Error('Downloaded wrong run');
 record('Download / return to saved run',downloaded.run_id);
 const before=(await (await page.request.get(base+'/api/runs')).json()).runs.length;
 await page.locator('[name="players"]').fill('0');await page.locator('#run-button').click();
 const invalid=await page.locator('[name="players"]').evaluate(el=>({valid:el.validity.valid,message:el.validationMessage}));
 record('Invalid settings',invalid);
 if(invalid.valid)throw Error('Zero-player input was accepted');
 const after=(await (await page.request.get(base+'/api/runs')).json()).runs.length;
 if(before!==after)throw Error('Invalid UI input created a run');
 await page.locator('[name="players"]').fill('24');
 await page.evaluate(()=>window.scrollTo(0,0));await shot('01-desktop');
 await page.setViewportSize({width:390,height:844});
 await page.evaluate(()=>window.scrollTo(0,0));await shot('05-mobile-top');
 await page.locator('#days-chart').scrollIntoViewIfNeeded();
 // The chart resize is deliberately debounced. Wait for its rendered width, not a fixed delay.
 await page.waitForFunction(()=>Math.abs(document.querySelector('#days-chart svg').viewBox.baseVal.width-document.querySelector('#days-chart').clientWidth)<1);
 await shot('06-mobile-chart');
 record('Narrow overflow',await page.evaluate(()=>({viewport:innerWidth,body:document.documentElement.scrollWidth,font:getComputedStyle(document.body).fontFamily})));
 if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1))throw Error('Page horizontally overflows on mobile');
 record('Browser errors',issues);if(issues.length)throw Error(issues.join('; '));
 observations.status='PASS';
} catch(error) {observations.status='FAIL';observations.error=error.stack;process.exitCode=1;}
finally {await fs.writeFile(path.join(out,'browser-observations.json'),JSON.stringify(observations,null,2));await browser.close();}
console.log(JSON.stringify(observations,null,2));
